worked on html
lilvina/calculator-benchmark pull request #1
Opened 2017-02-15 00:29 UTC by lilvina

2017-02-15 16:59 UTC, jrobcodes requested changes

2017-02-15 16:59 UTC, jrob8577 commented on index.html
> +    <div class="row1">
You could greatly simplify this HTML by removing many of these divs, using more targeted CSS selectors, and placing all of these divs under the `calculator` div (lines 9 through 10). I don't think any of the internal divs would be necessary - you could just create the buttons inline and position them with CSS:
```html
<div class="calculator">
  <p class="calculator-button">AC</p>
  <!-- all the buttons here -->
</div>
```
Note that the requirements state that class names are namespaced under the word "calculator", so `row` and `button-font` would be invalid class names. Finally, I would consider a different tag for the individual buttons - `p` (paragraph) doesn't seem semantically valid for this context.

2017-02-16 23:28 UTC, merged

2017-02-21 17:02 UTC, FrankieFabuloso commented on index.html
> +      <button class="positive/negative">+/-</button>
I would avoid putting '/' in any kind of identifier name just cause it has different meaning based on context. 
The convention seems to be that you write multi-word identifier names like:
class='I-am-more-than-one-word'

2017-02-21 17:05 UTC, jrob8577 commented on index.html
> +      <button class="positive/negative">+/-</button>
The convention used by google is lower snake case: `i_am_more_than_one_word`, or in this case, `positive_negative`

2017-02-21 17:06 UTC, FrankieFabuloso commented on index.html
> +  <div class="background">
Usualy when you want to center something on a browser window you wrap all the elements in a `<div class='container'></div>`.
So I suggest changing `background` to `container` and wrapping all of your `rows` in `<div class='container'>`

2017-02-21 17:07 UTC, FrankieFabuloso commented on index.html
> +      <button class="positive/negative">+/-</button>
That way your margin: auto will work in your CSS. :)